### ISSUE TITLE
Add text outline / shadow / glow

### ISSUE THREAD

**Issue by Nikoichu** [jameshnsears/QuoteUnquote#20]
Currently using the widget without any background cuz I don't like the colors available, but the white text clashes with the brighter colors on my wallpaper.

Is it possible to let the user select an outline or a glow effect for the text, and select ita color separately? That would allow users to customize it more, for example white glow for dark text, black glow (shadow) for white text and pink glow for quote gurus 😄 etc.

**Comment by jameshnsears** [comment]
Version 3.0.6, when released next, moves the colour selection from lists to a chooser. So lots of choice.

Can you explain the "glow" effect? Maybe give me an example. It might be possible to change how the text looks (beyond what's already available), but widget's are kind of limited in what you can do. So being a bit more specific would help me :-)

**Comment by Nikoichu** [comment]
I'd imagine it to work much like the effects in Photoshop:

Here it is currently without any glow/stroke:
![Screenshot_20220603-193222_Lawnchair](https://user-images.githubusercontent.com/42444745/172040095-9061a897-e419-467a-b856-8b7d455ec404.png)

With black stroke:
![Screenshot_20220603-193222_LawnchairO](https://user-images.githubusercontent.com/42444745/172040103-ee67d7ba-fceb-43ec-888b-7dbc7b0689e1.png)

With black glow: 
![Screenshot_20220603-193222_LawnchairG](https://user-images.githubusercontent.com/42444745/172040108-ddae9f51-1f83-468c-93b8-a49e364da82b.png)

With "Drop Shadow":
![Screenshot_20220603-193222_LawnchairDS](https://user-images.githubusercontent.com/42444745/172040199-34a261e1-b472-45a2-83b4-d6d354460ef7.png)


With funky fresh colors and glow:
![Screenshot_20220603-193222_LawnchairGC](https://user-images.githubusercontent.com/42444745/172040115-4d7e2bdc-58dc-49b9-893e-3b967a02e51f.png)

(Kinda hastily made mockups, but they do convey the idea lol)
Variables available to the user would be thickness, opacity, color, etc.

**Comment by jameshnsears** [comment]
It looks like adding some sort of shadow is possible - see: https://stackoverflow.com/questions/3297437/shadow-effect-for-a-text-in-android

I'll play around with something and see what I can come up with.

**Comment by jameshnsears** [comment]
HI - I have investigated some more. 

Android Apps allow you to change four parameters - Horizontal / Vertical / Radius / Colour - of a shadow (for text). 

However, a Widget - that resides on a Home Screen - is treated in a special way by Android, and does not support these four parameters!

It's possible for me to define hard coded values of these four parameters - but that's the best, well only, thing I can do (as far as I know). This means, that, for example, you will not be able to change the colour of the shadow.

On Appearance > Text > Style I could add something like:
Italic, Black Shadow
Regular, Black Shadow

If you'd like me to do this, then I can. But you'd have to tell me what colour shadow you'd like, as well as an example picture (so that I get an idea on how to do those other three parameters.

If you think this limitation is, well, too limiting, then let me know and I won't do anything except close this issue.

**Comment by Nikoichu** [comment]
@jameshnsears I see. That's unfortunate, but I think at least a "drop shadow" version would be nice to have, to separate bright text from bright backgrounds. For reference look at the mockups I posted above.

Thanks for taking the time to investigate and work on this! ❤️

**Comment by jameshnsears** [comment]
Hi - I have released 3.0.7 - which contains a solution to this issue.

It will take a few days for it to appear in Google Play & F-Droid.

Let me know if you spot a problem and I'll re-open this issue.
