### ISSUE TITLE
random advance should show any random quote

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#26]
Right now when you have seen all the quotes random advance just shows the last quote. Random advance should advance to a random quote even previously seen ones.

There should also be an option for random advance in the "recurring events". IE: so that on a phone unlock a truly random quote is switched to.

**Comment by jameshnsears** [comment]
tHi - at the moment either of the "Next" buttons stop advancing when you've exhausted whatever selection you've made. So the app is working as intended.

I'll investigate what you've suggested, maybe having some sort of switch that overrides the existing behaviour. But I won't start until after finishing the "quotation database / .csv" import feature I'm working on at the moment. 

Please keep the suggestions coming :-)

**Comment by Nikoichu** [comment]
I like it better the way it works right now, because if the random could show quotes you've already seen, then you'd never realistically see all of them, except if using sequential only.

The way I use the app is to show a new random quote each day (and manually whenever I feel like it) and fave the ones I agree with and like. So after however many years it takes me to go through all 18k quotes, I'll turn on the mode which cycles through my favorites. I'm currently at 1800 so 10% of the way there 😄

I'm not saying you should use the app the way I do, I'm just giving an example where the change you're suggesting would be detrimental. So if it's implemented, it would be nice to have a way to toggle it.

**Comment by nutpantz** [comment]
True random would randomly organize all quotes then show them one by one, preferably on a loop.

**Comment by jameshnsears** [comment]
Finally, managed to do this. Sorry it took so long.
