### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by francisbegbie** [jameshnsears/QuoteUnquote#31]
Version: 3.2.1-fdroid
Android: 11 (RQ3A.211001.001)

The regular format (Quote -> blank line -> Author -> blank line -> Count) is not adhered to whenever the widget displays quotes from 'Top Quotes'. As seen in the screenshot, the format changes to Quote -> Dash -> Author (on the same line) -> blank line -> Count.

Note: Setting is Configuration / Quotations / All. The above issue is encountered only when the app randomly picks quote from within 'Top Quotes'. No issue with other quotes.

![Screenshot_20220903-092116](https://user-images.githubusercontent.com/84503703/188574321-046a847e-2df4-498d-b067-cabbe21c00cd.png)

![Screenshot_20220903-092123](https://user-images.githubusercontent.com/84503703/188574339-c575e2f0-7f7f-45c1-9973-6db05c09b821.png)

**Comment by jameshnsears** [comment]
Hi - thanks for raising this issue and supplying the screenshots.

This is the case with quotes taken from https://www.reddit.com/r/quotes/ - /r/quotes/top

Basically I queried reddit's API - using python's praw library - for the top 1000 quotes. What comes back is a mess - excluding about 400 duplicates within the 1000 - the actual content doesn't split quotation from source.

If I had time I could manually do the split - but **at the moment** I haven't.

If someone else mentions or comments on this issue then I'll find time sooner rather than later. For the moment I'll keep this issue, open, under Enhancements in https://github.com/jameshnsears/QuoteUnquote/projects/1

**Comment by francisbegbie** [comment]
I know this would be time consuming if done manually. Not urgent, just wanted to bring to your attention.

**Comment by jameshnsears** [comment]
b6p5kzq3@...

One of the many things I like about this app is that I can click on the authors name to get a Wikipedia page about them. Unfortunately this is currently only possible if I select all or a specific author and not possible if I use "/r/quotes/top". Any chance of parsing the individual authors that appear here and adding the wikipedia link to it?

**Comment by jameshnsears** [comment]
Pushed a solution to this to Google Play and F-Droid. The Source is still called /r/quotes/top but if it's underlined it takes you to the relevant wikipedia article.

**Comment by francisbegbie** [comment]
Thank you James.
