### ISSUE TITLE
more cooler

### ISSUE THREAD

**Issue by herbtkip** [jameshnsears/QuoteUnquote#7]
**appreciation**
Wow.. this app is cream of the crop ... I really love it

**so what!**
Quyz... would ot be much cooler if you include the aready shown qouets ..that. is... when I have read a quotes from a specific specfic Author say .. Epictetus who has a collecton of 255..  I would want to wee the number added as read when I return back to view the all quotes section...
That is to mean if I was in no 100 in the all quotes/read section.. the new no.. should be 355 since I have already previewed the 255 from Epictetus..

thanks

**Comment by jameshnsears** [comment]
Hi herbert - thank your for raising the issue.

I think your idea is a good one. It's not an idea that I had thought of and it might not be too difficult to implement either. I'll investigate how to change the app.

You can track progress of your issue here: https://github.com/jameshnsears/QuoteUnquote/projects/1

**Comment by jameshnsears** [comment]
Hi - I have released version 2.6.2 with a possible solution to your issue.

The solution I came up with is a switch titled "Add displayed Author / Search to Previous" in the All section of the App.

The new version of the App should get picked up by Google Play within a couple of days or so. The app is also registered on fdroid - but their automated publishing process takes longer. 

Please re-open this issue if you spot a problem & thanks again for your suggestion.
