### ISSUE TITLE
example on csv file for import?

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#77]
Is there an example of the csv file needed for importing custom quotes. 
My old file no longer imports, want to check what is proper example

**Comment by jameshnsears** [comment]
Hi - it could be that the .csv import needs work. It's turned out the the library I'm using for .csv imports is far from perfect, but then again .csv might just be too "flexible" to import various data.

Anyway, there's a bunch of tests in the code and one of the tests features the following .csv

https://raw.githubusercontent.com/jameshnsears/QuoteUnquote/main/app/src/androidTest/assets/EmanuelKebede.csv

Let me know if you have any issues & I'll see what I can come up with as a solution.

**Comment by nutpantz** [comment]
Thanks for the example, with that and some googling i got it to work..(no empty lines allowed)
