### ISSUE TITLE
How do I export or download all 20000+ quotes in this app?

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [jameshnsears/QuoteUnquote#9]
Where do I do this? It would most likely be somewhere on GitHub.

**Comment by jameshnsears** [comment]
Hi - the quotations are stored in a SQLite database, that's shipped with the App:

https://github.com/jameshnsears/QuoteUnquote/blob/main/app/src/main/assets/quotations.db.prod

Download this file and open it with something like "DB Browser for SQLite": https://sqlitebrowser.org/dl/

You might need to remove the ".prod" from the filename, so that "DB Browser for SQLite" recognises the file.

Hope this helps.
